Use pydantic==1.* to avoid error
Error on import of opentoolflux.cli:

AttributeError: 'FieldInfo' object has no attribute 'Filter'

Not sure what is causing this, but staying with pydantic 1.* solves
the issue, for now.